# Generated by Django 6.0 on 2025-12-27 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_products_order_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='orders',
            field=models.ManyToManyField(related_name='items', through='api.OrderItem', to='api.product'),
        ),
    ]
